#!/bin/bash

# grpc public
find grpc/proto/public/. -type f -name "*.grpc.public.proto" -exec protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative {} \;

# grpc private
find grpc/proto/private/. -type f -name "*.grpc.private.proto" -exec protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative {} \;

